#!/usr/bin/env python
import rospy
import tf
import tf2_ros
from sensor_msgs.msg import Imu
from geometry_msgs.msg import TransformStamped
import tf.transformations as tft

class BaseLinkStabilizer:
    def __init__(self):
        rospy.init_node('base_stabilizer')

        # Load parameters
        self.imu_topic = rospy.get_param('~imu_topic', '/imu/data')
        self.base_frame = rospy.get_param('~base_frame', 'base_link')
        self.parent_frame = rospy.get_param('~parent_frame', 'odom')
        self.stabilized_frame = rospy.get_param('~stabilized_frame', 'base_link_stabilized')

        # TF interfaces
        self.tf_listener = tf.TransformListener()
        self.tf_broadcaster = tf2_ros.TransformBroadcaster()

        # Subscribe to IMU
        self.last_orientation = None
        rospy.Subscriber(self.imu_topic, Imu, self.imu_callback)

        # Publish at fixed rate
        rospy.Timer(rospy.Duration(0.02), self.timer_callback)

    def imu_callback(self, msg):
        q = msg.orientation
        self.last_orientation = [q.x, q.y, q.z, q.w]

    def timer_callback(self, event):
        if self.last_orientation is None:
            return

        try:
            (trans, rot) = self.tf_listener.lookupTransform(self.parent_frame, self.base_frame, rospy.Time(0))
        except (tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException):
            return

        # Extract yaw from IMU quaternion
        _, _, yaw = tft.euler_from_quaternion(self.last_orientation)
        yaw_only_q = tft.quaternion_from_euler(0.0, 0.0, yaw)

        # Create and publish stabilized transform
        t = TransformStamped()
        t.header.stamp = rospy.Time.now()
        t.header.frame_id = self.parent_frame
        t.child_frame_id = self.stabilized_frame
        t.transform.translation.x = trans[0]
        t.transform.translation.y = trans[1]
        t.transform.translation.z = trans[2]
        t.transform.rotation.x = yaw_only_q[0]
        t.transform.rotation.y = yaw_only_q[1]
        t.transform.rotation.z = yaw_only_q[2]
        t.transform.rotation.w = yaw_only_q[3]

        self.tf_broadcaster.sendTransform(t)

if __name__ == '__main__':
    try:
        BaseLinkStabilizer()
        rospy.spin()
    except rospy.ROSInterruptException:
        pass

